//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SproutPayrollCalculator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPayrollEntities : DbContext
    {
        public DBPayrollEntities()
            : base("name=DBPayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GsisTable> GsisTables { get; set; }
        public virtual DbSet<PagibigTable> PagibigTables { get; set; }
        public virtual DbSet<PhilhealthTable> PhilhealthTables { get; set; }
        public virtual DbSet<SssTable> SssTables { get; set; }
        public virtual DbSet<TaxTable> TaxTables { get; set; }
        public virtual DbSet<TaxTableExemption> TaxTableExemptions { get; set; }
    }
}
