//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SproutPayrollCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SssTable
    {
        public Nullable<double> rangeMin { get; set; }
        public Nullable<double> rangeMax { get; set; }
        public double contribution { get; set; }
    }
}
