//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SproutPayrollCalculator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxTable
    {
        public string status { get; set; }
        public int bracket { get; set; }
        public double rangeMax { get; set; }
        public bool period { get; set; }
    }
}
